
spring:
  redis:
    port: 6379
    host: 127.0.0.1
    timeout: 200
    password:
    database: 0
    jedis:
      pool:
        max-idle: 20
        min-idle: 0
        max-active: 50
        max-wait: -1ms